#!/usr/bin/env python3
"""Layer completion gate for DB → API → frontend SDLC sequencing.

Validates that layer-specific evidence exists before a PR can be considered done.
It does not replace real tests; it blocks missing or placeholder evidence and writes
layer pass files consumed by the next automation cycle.
"""
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Dict, List

PLACEHOLDER_MARKERS = [
    "PENDING_AGENT_VERIFICATION",
    "Generated by automation. Agents should replace",
    "PM decision: Pending",
    "TODO",
    "TBD",
]

BASE_REQUIRED = [
    "agents.log.md",
    "qa-checklist.md",
    "pm-checklist.md",
    "test-evidence.md",
    "scale-security-architecture-review.md",
    "pr-notification.md",
]

LAYER_RULES = {
    "database": {
        "keywords": ["database", "db", "schema", "model", "repository", "migration", "integration"],
        "must_include_any": ["integration", "test"],
        "description": "Database/data model layer needs schema/model validation and DB integration evidence.",
    },
    "api": {
        "keywords": ["api", "contract", "endpoint", "backend", "integration", "database"],
        "must_include_any": ["contract", "integration"],
        "description": "API/backend layer needs contract tests and DB-backed integration evidence.",
    },
    "frontend": {
        "keywords": ["frontend", "component", "screen", "ui", "e2e", "accessibility", "visual"],
        "must_include_any": ["component", "e2e", "integration"],
        "description": "Frontend layer needs component, visual/accessibility, and real API/E2E evidence when applicable.",
    },
    "cloud": {
        "keywords": ["terraform", "plan", "validate", "aws", "cloud"],
        "must_include_any": ["terraform", "plan"],
        "description": "Cloud layer needs Terraform fmt/validate/plan evidence.",
    },
    "design": {
        "keywords": ["architecture", "design", "data model", "api", "testing strategy", "paradigm"],
        "must_include_any": ["architecture", "design"],
        "description": "Design layer needs architecture, data/API/cloud, test, and paradigm decisions.",
    },
}


def read(path: Path) -> str:
    return path.read_text(encoding="utf-8", errors="replace") if path.exists() else ""


def evaluate(layer: str, evidence_dir: Path, ui_change: bool, cloud_change: bool) -> Dict[str, object]:
    failures: List[str] = []
    warnings: List[str] = []
    files: Dict[str, Dict[str, object]] = {}
    combined_parts: List[str] = []
    for rel in BASE_REQUIRED:
        path = evidence_dir / rel
        content = read(path)
        files[rel] = {"exists": path.exists(), "bytes": len(content)}
        if not path.exists() or not content.strip():
            failures.append(f"Missing evidence file: {evidence_dir / rel}")
        else:
            combined_parts.append(content)
            for marker in PLACEHOLDER_MARKERS:
                if marker in content:
                    failures.append(f"Placeholder marker `{marker}` remains in {evidence_dir / rel}")
    combined = "\n".join(combined_parts).lower()
    rule = LAYER_RULES.get(layer, {"keywords": [], "must_include_any": [], "description": "Generic layer gate."})
    if layer in LAYER_RULES:
        if not any(k in combined for k in rule["must_include_any"]):
            failures.append(f"{layer} evidence does not include expected proof: one of {rule['must_include_any']}")
    if ui_change:
        visual = read(evidence_dir / "visual-evidence.md")
        if not visual.strip():
            failures.append("UI change requires visual-evidence.md with screenshots/annotations or a concrete environment blocker.")
        elif any(m in visual for m in PLACEHOLDER_MARKERS):
            failures.append("visual-evidence.md still contains placeholder markers.")
    if cloud_change and "terraform" not in combined:
        failures.append("Cloud/AWS change requires Terraform evidence.")
    if layer == "frontend" and ("mock" in combined and "real api" not in combined and "e2e" not in combined):
        warnings.append("Frontend evidence mentions mocks; ensure real API/E2E is present before marking done.")
    return {
        "status": "PASS" if not failures else "FAIL",
        "layer": layer,
        "failures": failures,
        "warnings": warnings,
        "files": files,
        "rule": rule.get("description", "Generic layer gate."),
    }


def markdown(report: Dict[str, object], evidence_dir: Path) -> str:
    lines = ["# Layer Gate Report", "", f"Layer: `{report['layer']}`", f"Evidence: `{evidence_dir}`", f"Status: **{report['status']}**", "", f"Rule: {report.get('rule')}" , ""]
    if report.get("failures"):
        lines.extend(["## Blocking findings", ""])
        lines.extend(f"- {x}" for x in report["failures"])
        lines.append("")
    if report.get("warnings"):
        lines.extend(["## Warnings", ""])
        lines.extend(f"- {x}" for x in report["warnings"])
        lines.append("")
    lines.extend(["## Evidence files", "", "| File | Exists | Bytes |", "|---|---:|---:|"])
    for rel, data in (report.get("files") or {}).items():
        lines.append(f"| `{rel}` | {data.get('exists')} | {data.get('bytes')} |")
    lines.extend(["", "## Dependency order", "", "Database/data model must pass before API/backend. API/backend must pass before frontend. Frontend mocks are not final integration evidence."])
    return "\n".join(lines) + "\n"


def write_pass_files(pass_dir: Path, layer: str, spec_id: str, task_id: str, report: Dict[str, object]) -> None:
    pass_dir.mkdir(parents=True, exist_ok=True)
    payload = {
        "schema": "agentic.layer-gate.v1",
        "status": "PASS",
        "layer": layer,
        "spec_id": spec_id,
        "task_id": task_id,
        "rule": report.get("rule"),
    }
    (pass_dir / f"{layer}.passed.json").write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    (pass_dir / f"{layer}.passed.md").write_text(
        f"# {layer.title()} Layer Gate\n\nStatus: PASS\n\nSpec: `{spec_id}`\nTask: `{task_id}`\n\nRule: {report.get('rule')}\n",
        encoding="utf-8",
    )


def main() -> int:
    p = argparse.ArgumentParser(description="Validate layer-specific QA evidence.")
    p.add_argument("--layer", required=True, choices=["design", "cloud", "database", "api", "backend", "frontend", "qa", "pm", "release", "crosscutting"])
    p.add_argument("--spec-id", required=True)
    p.add_argument("--task-id", required=True)
    p.add_argument("--evidence-dir", required=True, type=Path)
    p.add_argument("--pass-dir", required=True, type=Path)
    p.add_argument("--write-pass-file", action="store_true")
    p.add_argument("--ui-change", action="store_true")
    p.add_argument("--cloud-change", action="store_true")
    p.add_argument("--format", choices=["json", "markdown"], default="markdown")
    p.add_argument("--markdown-output", type=Path)
    args = p.parse_args()
    layer = "api" if args.layer == "backend" else args.layer
    report = evaluate(layer, args.evidence_dir, ui_change=args.ui_change, cloud_change=args.cloud_change)
    md = markdown(report, args.evidence_dir)
    if args.markdown_output:
        args.markdown_output.parent.mkdir(parents=True, exist_ok=True)
        args.markdown_output.write_text(md, encoding="utf-8")
    if report["status"] == "PASS" and args.write_pass_file:
        write_pass_files(args.pass_dir, layer, args.spec_id, args.task_id, report)
    if args.format == "json":
        print(json.dumps(report, indent=2, sort_keys=True))
    else:
        print(md)
    return 0 if report["status"] == "PASS" else 1


if __name__ == "__main__":
    raise SystemExit(main())
